name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Triggers deployment when pushing to main branch

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Google Cloud SDK
        run: gcloud auth configure-docker

      - name: Set up Google Cloud Project and Region
        run: |
          gcloud config set project $PROJECT_ID
          gcloud config set run/region $REGION

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/$PROJECT_ID/saas-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy saas-app \
            --image gcr.io/$PROJECT_ID/saas-app \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated

